<?php
/**
 * GENERATED BY GLS SOAP GENERATOR
 * DO NOT EDIT MANUALLY
 *
 * Generator klas SOAP 1:1 z WSDL, ale z nazwami klas zgodnymi z PSR-4:
 *  - WSDL: cConsign            -> PHP: CConsign
 *  - WSDL: adeLoginRequest     -> PHP: AdeLoginRequest
 *
 * Nazwy pól/właściwości pozostają 1:1 jak w WSDL (np. invoice_num, srv_ade).
 *
 * Dodatkowo generuje Classmap.php, który mapuje WSDL typename -> PHP class.
 *
 * Użycie:
 *   php tools/generate-soap.php gls.wsdl.txt src/Soap "Kerogos\\GlsPolska\\Soap" --clean
 *
 * Argumenty pozycyjne:
 *   1) ścieżka do WSDL (domyślnie: gls.wsdl.txt)
 *   2) katalog wyjściowy (domyślnie: ../src/Soap)
 *   3) namespace (domyślnie: Kerogos\GlsPolska\Soap)
 *
 * Flagi:
 *   --clean  usuwa przed generacją tylko pliki oznaczone markerem GENERATED BY GLS SOAP GENERATOR
 */

declare(strict_types=1);

const GLS_GENERATOR_MARKER = 'GENERATED BY GLS SOAP GENERATOR';

$argvCopy = $argv ?? [];
$flags = [];
$positional = [];

foreach ($argvCopy as $i => $arg) {
	if ($i === 0) continue;
	if (strpos($arg, '--') === 0) {
		$flags[] = $arg;
	} else {
		$positional[] = $arg;
	}
}

$clean    = in_array('--clean', $flags, true);
$wsdlPath = $positional[0] ?? 'gls.wsdl.txt';
$outDir   = $positional[1] ?? (__DIR__ . '/../src/Soap');
$ns       = $positional[2] ?? 'Kerogos\\GlsPolska\\Soap';

if (!is_file($wsdlPath)) {
	fwrite(STDERR, "WSDL not found: {$wsdlPath}\n");
	exit(1);
}

if (!is_dir($outDir) && !mkdir($outDir, 0777, true) && !is_dir($outDir)) {
	fwrite(STDERR, "Cannot create output dir: {$outDir}\n");
	exit(1);
}

/**
 * CLEAN: usuwa wyłącznie pliki oznaczone markerem.
 */
$cleanOutputDir = static function (string $dir): void {
	if (!is_dir($dir)) return;
	
	$files = glob(rtrim($dir, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . '*.php');
	if (!$files) return;
	
	foreach ($files as $file) {
		$content = @file_get_contents($file);
		if ($content === false) continue;
		
		if (strpos($content, GLS_GENERATOR_MARKER) !== false) {
			@unlink($file);
		}
	}
};

if ($clean) {
	$cleanOutputDir($outDir);
}

$xml = file_get_contents($wsdlPath);
if ($xml === false) {
	fwrite(STDERR, "Cannot read WSDL: {$wsdlPath}\n");
	exit(1);
}

libxml_use_internal_errors(true);

$dom = new DOMDocument();
$dom->preserveWhiteSpace = false;
$dom->formatOutput = false;

if (!$dom->loadXML($xml)) {
	fwrite(STDERR, "Invalid XML in WSDL.\n");
	foreach (libxml_get_errors() as $err) {
		fwrite(STDERR, trim($err->message) . "\n");
	}
	exit(1);
}

$xp = new DOMXPath($dom);

// Typowe namespace’y dla WSDL/XSD (Twoje WSDL to standardowy WSDL + XSD). [1](https://onedrive.live.com?cid=F8C719A0761A033D&id=F8C719A0761A033D!s5902c42a16ea40dd988ad9049868b668)
$xp->registerNamespace('wsdl', 'http://schemas.xmlsoap.org/wsdl/');
$xp->registerNamespace('xsd',  'http://www.w3.org/2001/XMLSchema');
$xp->registerNamespace('xs',   'http://www.w3.org/2001/XMLSchema');

/**
 * PSR-4: tylko pierwsza litera wielka (bez innych transformacji).
 */
$toClassName = static function (string $wsdlName): string {
	return ucfirst($wsdlName);
};

$isValidPhpIdentifier = static function (string $name): bool {
	return (bool)preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $name);
};

/**
 * Mapowanie typów na PHPDoc:
 * - xsd:* na skalar (string/int/float/bool)
 * - typy niestandardowe (np. tns:cConsign) -> PSR-4 class name (ucfirst local)
 */
$mapWsdlTypeToDoc = static function (?string $type) use ($toClassName): string {
	if ($type === null || $type === '') return 'mixed';
	
	if (strpos($type, ':') !== false) {
		[$prefix, $local] = explode(':', $type, 2);
		
		if ($prefix === 'xsd' || $prefix === 'xs') {
			switch ($local) {
				case 'string': return 'string';
				case 'boolean': return 'bool';
				case 'int':
				case 'integer':
				case 'long':
				case 'short':
				case 'byte': return 'int';
				case 'float':
				case 'double':
				case 'decimal': return 'float';
				case 'date':
				case 'dateTime':
				case 'time':
				case 'base64Binary': return 'string';
				default: return 'string';
			}
		}
		
		// custom type (tns:..., soapenc:..., etc.) -> local as class name (PSR-4)
		return $toClassName($local);
	}
	
	// bez prefixu
	return $toClassName($type);
};

$findComplexTypes = static function (DOMXPath $xp): array {
	$nodes = $xp->query('//xsd:complexType | //xs:complexType');
	$out = [];
	if (!$nodes) return $out;
	
	/** @var DOMElement $ct */
	foreach ($nodes as $ct) {
		$name = $ct->getAttribute('name');
		if ($name) {
			$out[$name] = $ct;
		}
	}
	return $out;
};

/**
 * Wyciąga pola z complexType, ale DEDUPLIKUJE po nazwie elementu,
 * żeby nie było powieleń (Twój problem).
 */
$extractElements = static function (DOMXPath $xp, DOMElement $complexType): array {
	$paths = [
		'./xsd:sequence/xsd:element', './xs:sequence/xs:element',
		'./xsd:all/xsd:element',      './xs:all/xs:element',
		'./xsd:complexContent/xsd:extension/xsd:sequence/xsd:element',
		'./xs:complexContent/xs:extension/xs:sequence/xs:element',
		'./xsd:complexContent/xsd:extension/xsd:all/xsd:element',
		'./xs:complexContent/xs:extension/xs:all/xs:element',
	];
	
	$elementsByName = []; // name => element info
	
	foreach ($paths as $path) {
		$nodes = $xp->query($path, $complexType);
		if (!$nodes) continue;
		
		/** @var DOMElement $el */
		foreach ($nodes as $el) {
			$name = $el->getAttribute('name');
			if ($name === '') continue;
			
			// ✅ deduplikacja: jeśli już mamy element o tej nazwie, pomijamy
			if (isset($elementsByName[$name])) continue;
			
			$elementsByName[$name] = [
				'name'      => $name,
				'type'      => $el->getAttribute('type') ?: null,
				'minOccurs' => $el->getAttribute('minOccurs') ?: null,
				'maxOccurs' => $el->getAttribute('maxOccurs') ?: null,
				'nillable'  => $el->getAttribute('nillable') ?: null,
			];
		}
	}
	
	return array_values($elementsByName);
};

$complexTypes = $findComplexTypes($xp);

$classmap = []; // wsdlTypeName => \Namespace\Class

foreach ($complexTypes as $wsdlTypeName => $ctNode) {
	$className = $toClassName($wsdlTypeName);
	$fqcn = '\\' . trim($ns, '\\') . '\\' . $className;
	$classmap[$wsdlTypeName] = $fqcn;
	
	$elements = $extractElements($xp, $ctNode);
	
	$props = [];
	$warnings = [];
	
	foreach ($elements as $el) {
		$propName = $el['name'];
		if (!$propName) continue;
		
		if (!$isValidPhpIdentifier($propName)) {
			// WSDL 1:1: jeśli trafi się coś nie-php, ostrzegamy w komentarzu.
			$warnings[] = "UWAGA: pole '{$propName}' nie jest poprawnym identyfikatorem PHP i nie zostało wygenerowane.";
			continue;
		}
		
		$docType = $mapWsdlTypeToDoc($el['type']);
		
		$maxOccurs = $el['maxOccurs'];
		$isArray = ($maxOccurs === 'unbounded') || (is_numeric($maxOccurs) && (int)$maxOccurs > 1);
		
		if ($isArray) {
			$docType .= '[]';
		}
		
		$props[] =
			"    /** @var {$docType}|null */\n" .
			"    public \${$propName} = null;\n";
	}
	
	$warningBlock = '';
	if ($warnings) {
		$warningBlock = "/**\n" . implode("\n", array_map(static fn($w) => " * {$w}", $warnings)) . "\n */\n\n";
	}
	
	$php =
		"<?php\n" .
		"/**\n" .
		" * " . GLS_GENERATOR_MARKER . "\n" .
		" * DO NOT EDIT MANUALLY\n" .
		" */\n\n" .
		"declare(strict_types=1);\n\n" .
		"namespace {$ns};\n\n" .
		$warningBlock .
		"class {$className}\n{\n" .
		($props ? ("\n" . implode("\n", $props)) : "    // Brak pól w schema dla tego typu.\n") .
		"}\n";
	
	file_put_contents(rtrim($outDir, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $className . '.php', $php);
}

// Generujemy Classmap.php (też oznaczony markerem, żeby CLEAN mógł go wymienić)
$classmapPhp =
	"<?php\n" .
	"/**\n" .
	" * " . GLS_GENERATOR_MARKER . "\n" .
	" * DO NOT EDIT MANUALLY\n" .
	" */\n\n" .
	"declare(strict_types=1);\n\n" .
	"namespace {$ns};\n\n" .
	"final class Classmap\n{\n" .
	"    public static function get(): array\n" .
	"    {\n" .
	"        return [\n";

foreach ($classmap as $wsdlName => $fqcn) {
	// $fqcn już ma wiodący backslash
	$classmapPhp .= "            '{$wsdlName}' => {$fqcn}::class,\n";
}

$classmapPhp .=
	"        ];\n" .
	"    }\n" .
	"}\n";

file_put_contents(rtrim($outDir, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . 'Classmap.php', $classmapPhp);

echo "OK. Wygenerowano klasy do: {$outDir}\n";
echo "Dodano/odświeżono: {$outDir}/Classmap.php\n";
if ($clean) {
	echo "CLEAN: usunięto poprzednie pliki oznaczone markerem.\n";
}